service: serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  list:
    handler: index.list
    events:
      - httpApi:
          path: /list
          method: get
  get:
    handler: index.get
    events:
      - httpApi:
          path: /get
          method: get
  http:
    handler: index.get
    events:
      - http:
          path: /http
          method: get
  post:
    handler: index.post
    events:
      - httpApi:
          path: /post
          method: post

plugins:
  - serverless-plugin-typescript
